/** Categories for grouping in RBC design gallery (order of sections). */
export const CARD_DESIGN_CATEGORY_ORDER = [
  'Basic',
  'Marble',
  'Original',
  'Luxury',
  'Nature',
  'Special',
  'Branches',
  'Realistic',
] as const;

export type CardDesignCategory = (typeof CARD_DESIGN_CATEGORY_ORDER)[number];

export interface CardDesign {
  id: string;
  name: string;
  type: 'gradient' | 'image';
  category: CardDesignCategory;
  gradientColors?: string[];
  gradientStart?: { x: number; y: number };
  gradientEnd?: { x: number; y: number };
  frontImage?: unknown;
  backImage?: unknown;
  textColor: string;
}

export const cardDesigns: CardDesign[] = [
  {
    id: 'default',
    name: 'Classic',
    type: 'gradient',
    category: 'Basic',
    gradientColors: ['#667eea', '#764ba2'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  {
    id: 'dark',
    name: 'Dark',
    type: 'gradient',
    category: 'Basic',
    gradientColors: ['#1a1a1a', '#2d2d2d'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  {
    id: 'red',
    name: 'Red',
    type: 'gradient',
    category: 'Basic',
    gradientColors: ['#dc2626', '#991b1b'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  {
    id: 'blue',
    name: 'Blue',
    type: 'gradient',
    category: 'Basic',
    gradientColors: ['#3b82f6', '#1e40af'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  {
    id: 'marble-white',
    name: 'Marble White',
    type: 'gradient',
    category: 'Marble',
    gradientColors: ['#f5f5f5', '#e8e8e8', '#f0f0f0'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: '#1a1a1a',
  },
  {
    id: 'marble-gold',
    name: 'Marble Gold',
    type: 'gradient',
    category: 'Marble',
    gradientColors: ['#fef3c7', '#fde68a', '#fcd34d'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: '#78350f',
  },
  {
    id: 'original-blue',
    name: 'Original Blue',
    type: 'gradient',
    category: 'Original',
    gradientColors: ['#0055ff', '#0046d1'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  {
    id: 'original-orange',
    name: 'Original Orange',
    type: 'gradient',
    category: 'Original',
    gradientColors: ['#ff6600', '#d75400'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  {
    id: 'luxury-onyx',
    name: 'Luxury Onyx',
    type: 'gradient',
    category: 'Luxury',
    gradientColors: ['#09090b', '#111827'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    type: 'gradient',
    category: 'Luxury',
    gradientColors: ['#f8e7bd', '#d9a441', '#f3d58a'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: '#4a2c0a',
  },
  {
    id: 'nature-forest',
    name: 'Nature Forest',
    type: 'gradient',
    category: 'Nature',
    gradientColors: ['#0b3d2e', '#1f5f3a'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  {
    id: 'nature-lake',
    name: 'Nature Lake',
    type: 'gradient',
    category: 'Nature',
    gradientColors: ['#0f4c5c', '#1b6d7c'],
    gradientStart: { x: 0, y: 0 },
    gradientEnd: { x: 1, y: 1 },
    textColor: 'white',
  },
  // --- Image: Special ---
  {
    id: 'card-1',
    name: 'Christmas',
    type: 'image',
    category: 'Special',
    frontImage: require('../assets/cards/card-1.png'),
    backImage: require('../assets/cards/card-1.png'),
    textColor: 'white',
  },
  {
    id: 'marble-black',
    name: 'Black Marble',
    type: 'image',
    category: 'Special',
    frontImage: require('../assets/cards/card-black-marble.png'),
    backImage: require('../assets/cards/card-black-marble.png'),
    textColor: 'white',
  },
  {
    id: 'thnx-rb',
    name: 'THNX RB',
    type: 'image',
    category: 'Special',
    frontImage: require('../assets/cards/card-thnx-back.png'),
    backImage: require('../assets/cards/card-thnx-front.png'),
    textColor: 'white',
  },
  {
    id: 'nebonic',
    name: '#nebonic!',
    type: 'image',
    category: 'Special',
    frontImage: require('../assets/cards/card-nebonic.png'),
    backImage: require('../assets/cards/card-nebonic.png'),
    textColor: 'white',
  },
  // --- Image: Branches ---
  {
    id: 'branch-modrany',
    name: 'Modřany',
    type: 'image',
    category: 'Branches',
    frontImage: require('../assets/cards/card-branch-modrany.webp'),
    backImage: require('../assets/cards/card-branch-modrany.webp'),
    textColor: 'white',
  },
  {
    id: 'branch-kacerov',
    name: 'Kačerov',
    type: 'image',
    category: 'Branches',
    frontImage: require('../assets/cards/card-branch-kacerov.webp'),
    backImage: require('../assets/cards/card-branch-kacerov.webp'),
    textColor: 'white',
  },
  {
    id: 'branch-hagibor',
    name: 'Hagibor',
    type: 'image',
    category: 'Branches',
    frontImage: require('../assets/cards/card-branch-hagibor.webp'),
    backImage: require('../assets/cards/card-branch-hagibor.webp'),
    textColor: 'white',
  },
  {
    id: 'branch-barrandov',
    name: 'Barrandov',
    type: 'image',
    category: 'Branches',
    frontImage: require('../assets/cards/card-branch-barrandov.webp'),
    backImage: require('../assets/cards/card-branch-barrandov.webp'),
    textColor: 'white',
  },
  // --- Image: Realistic ---
  {
    id: 'gallery-realistic-1',
    name: 'Realistic 1',
    type: 'image',
    category: 'Realistic',
    frontImage: require('../assets/cards/card-realistic-1.webp'),
    backImage: require('../assets/cards/card-realistic-1.webp'),
    textColor: 'white',
  },
  {
    id: 'gallery-realistic-2',
    name: 'Realistic 2',
    type: 'image',
    category: 'Realistic',
    frontImage: require('../assets/cards/card-realistic-2.webp'),
    backImage: require('../assets/cards/card-realistic-2.webp'),
    textColor: 'white',
  },
  {
    id: 'gallery-realistic-3',
    name: 'Realistic 3',
    type: 'image',
    category: 'Realistic',
    frontImage: require('../assets/cards/card-realistic-3.webp'),
    backImage: require('../assets/cards/card-realistic-3.webp'),
    textColor: 'white',
  },
];

export const RBC_SELECTED_CARD_KEY = '@rbc_selected_card_design';
